github:
  description: "Working Groups Documents for the Apache Community Development"
  homepage: https://community.apache.org/
  labels:
    - apache
    - community
    - comdev

  rulesets:
    - name: "Default Branch Protection"
      type: branch
      branches:
        includes:
          - "~DEFAULT_BRANCH"
          - "release/*"
          - "rel/*"
        excludes: []
      bypass_teams:
        - root
      restrict_deletion: true
      restrict_force_push: true
notifications:
  commits: commits@community.apache.org
  issues: notifications@community.apache.org
  pullrequests: notifications@community.apache.org
  jira_options: link label
